[package]
name = "kvs"
version = "0.1.0"
authors = ["XFFXFF <1247714429@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
